apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZGI6NTQzMi91c2VyZGI=
  SPRING_DATASOURCE_USERNAME: dXNlcmRi
  SPRING_DATASOURCE_PASSWORD: c2VjcmV0
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleQ==
